#Web-server params
server:
  port: ${PORT:8080}

#Telegram params
telegram:
  chat-id: ${TG_CHANNEL_ID}
  bot:
    token: ${TG_BOT_TOKEN}
    name: ${TG_BOT_NAME}
  sending:
    ignore-error: false
    retry:
      max-attempts: 3
      delay: 10000

#GPX Animator params
gpx-animator-app:
  path: gpx-animator-app.jar
  executionTimeout: 3m
  outputFormat: MP4
  outWidth: 1024
  outHeight: 1024
  background-map-visibility: 0.75
  fps: 60

system:
  #Main params
  input-file-max-size: 5MB
  work-dir: ${WORK_DIR}
  rate-limiting:
    enabled: true
    limits:
      - requests: 1
        period: 1m
      - requests: 25
        period: 1d

retryer:
  maxAttempts: 3
  period: 100ms
  maxPeriod: 1s

external:
  geocoder:
    url: https://photon.komoot.io/

feign:
  client:
    config:
      default:
        connectTimeout: 100
        readTimeout: 500
        loggerLevel: basic
        decode404: false
        retryer: com.anagorny.gpxanimatorbot.services.impl.RetryerImpl

#Logging params
logging:
  pattern:
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint}[%X{correlationId}] %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"
    file: ${logging.pattern.console}

  level:
    root: INFO
    com.anagorny.gpxanimatorbot.clients: DEBUG
    com.anagorny.gpxanimatorbot.services.impl.GpxAnimatorRunnerImpl: DEBUG
  file:
    name: ${WORK_DIR}/logs/gpx-animator-telegram-bot.log
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB
